os:
  - linux
services:
  - docker
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

script:
  - chmod +x mvnw
  - ./mvnw clean test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
