version: '2'
services:
  students-app:
    image: testmongospring
    environment:
    - _JAVA_OPTIONS=-Xmx512m -Xms256m
    - SPRING_PROFILES_ACTIVE=prod
#    - SPRING_DATASOURCE_URL=jdbc:mariadb://students-mariadb:30022/students
    - SPRING_MYSQL_JDBC_URL=jdbc:mariadb://students-mariadb:3306/students

    - SPRING_DATA_MONGODB_URI=mongodb://students-mongodb:27017
    - SPRING_DATA_MONGODB_DATABASE=students
    - STUDENTS_SLEEP=10 # gives time for the database to boot before the application
    ports:
    - 8080:8080

  students-mariadb:
    extends:
      file: mariadb.yml
      service: students-mariadb

  students-mongodb:
    extends:
      file: mongodb.yml
      service: students-mongodb
