version: '2'
services:
    students-mariadb:
        container_name: students-mariadb
        image: mariadb:10.3.7

        environment:
#            - MYSQL_HOST: localhost
            - MYSQL_USER=student
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=students


        volumes:
            - "./volumes/students/mysql_init.sql:/usr/local/bin/mysql_init.sql"
            - "./volumes/students/mysql_init.sql:/docker-entrypoint-initdb.d/dump.sql"
        ports:
        - 3386:3306






