version: '2'
services:
    students-mariadb:
        container_name: students-mariadb
        image: mariadb:10.3.7

        environment:
#            - MYSQL_HOST: localhost
            - MYSQL_USER=student
            - MYSQL_ROOT_PASSWORD=test123
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=students
            - SPRING_MYSQL_JDBC_URL=jdbc:mysql://172.10.18.2:3386/students?useUnicode=true&characterEncoding=utf8&useSSL=false


        volumes:
            - "./volumes/students/mysql_init.sql:/usr/local/bin/mysql_init.sql"
            - "./volumes/students/mysql_init.sql:/docker-entrypoint-initdb.d/dump.sql"
        ports:
        - 3386:3306






