version: '2'
services:
    students-mariadb:
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/students/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=students
        ports:
            - 30022:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
