version: '2'
services:
    students-postgresql:
        container_name: students-postgresql
        image: postgres:11
#        volumes:
#           - ./volumes/students/students/postgres_messages.sql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=1234
        ports:
            - 5432:5432
