version: '2'
services:
    students-postgresql:
        image: postgres:11
        # volumes:
        #     - ~/volumes/students/students/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=1234
        ports:
            - 5432:5432
